<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Data\quan_huyen.json" />
    <None Remove="Data\tinh_tp.json" />
    <None Remove="Data\xa_phuong.json" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Data\tinh_tp.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AdditionalFiles>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\quan_huyen.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\xa_phuong.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Emgu.CV" Version="4.12.0.5764" />
    <PackageReference Include="Emgu.CV.runtime.windows" Version="4.12.0.5764" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Select.HtmlToPdf" Version="25.2.0" />
    <PackageReference Include="Select.HtmlToPdf.NetCore" Version="25.2.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DTO\DTO.csproj" />
  </ItemGroup>

</Project>
